# Generated by Django 3.2.6 on 2021-08-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_profile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='schedules',
            new_name='drugstores',
        ),
    ]
