# Generated by Django 3.2.6 on 2021-08-05 14:18

import application.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='file',
            field=models.FileField(upload_to='', validators=[application.validators.validate_file_extension]),
        ),
    ]
